// UNVERIFIED — written without a compiler in this environment. Requires Xcode/Android Studio + signing to build and validate.
//
// iOS native transport probe (R6). Taps MultipeerConnectivity's MCSession
// send + didReceive, emits os_signpost intervals for native-layer latency, and
// forwards L2-schema events into the JS collector via the TurboModule event
// emitter.
//
// This file is a SWIFT SOURCE ONLY. It has NOT been compiled, linked, run, or
// profiled. There is no iOS toolchain in this environment (xcodebuild/swift are
// absent per docs/02 C15). Field names below are copied byte-for-byte from the
// frozen JS schema (src/sink.ts L2Event) and the L0 envelope
// (hrpc-inspector-protocol/envelope.ts P2PEnvelope) so that wiring on a real
// toolchain is mechanical, not a redesign.

import Foundation
import MultipeerConnectivity
import os.signpost

// MARK: - os_signpost log handle
//
// One dedicated OSLog subsystem/category so Instruments' "Points of Interest" /
// custom os_signpost lane isolates native transport latency from app noise.
// NOTE (C17, UNVERIFIED): the runtime overhead of these signpost calls has NOT
// been measured. It cannot be measured without a device + Instruments. Do not
// quote a number for it.
let p2pSignpostLog = OSLog(subsystem: "io.tether.p2p.probe", category: "transport")

// MARK: - L2 event field names (FROZEN — must match JS schema exactly)
//
// These strings are the JS-side keys. Changing any one silently breaks
// event-shape parity with the JS adapters (sink.ts) and the L4 panel. The
// native side populates the same union member `type` values the JS adapters do.
enum L2Field {
    static let type = "type"          // L2EventType, e.g. "message.out" / "message.in"
    static let t = "t"                // monotonic timestamp (native mach time -> ms)
    static let msgId = "msgId"        // ULID
    static let corrId = "corrId"      // request/response correlation id
    static let method = "method"      // pseudo-URL, e.g. "blocks.fetch"
    static let kind = "kind"          // req|res|event|ack|err
    static let src = "src"            // sender PeerId
    static let dst = "dst"            // recipient PeerId or "*"
    static let ts = "ts"              // sender wall clock (epoch ms), untrusted
    static let hlc = "hlc"            // "phys:ctr:node"
    static let bytes = "bytes"        // payload byte length
    static let transport = "transport" // constant "multipeer" for this probe
    static let peerId = "peerId"      // spine field shared with JS adapters
}

// Transport tag for every event this probe emits.
private let kTransport = "multipeer"

// MARK: - Monotonic clock
//
// JS adapters use performance.now()-style monotonic ms. Mirror that with
// mach_absolute_time so native `t` values are comparable in kind (a monotonic
// millisecond counter), not wall clock.
private func monotonicMillis() -> Double {
    var info = mach_timebase_info_data_t()
    mach_timebase_info(&info)
    let nanos = Double(mach_absolute_time()) * Double(info.numer) / Double(info.denom)
    return nanos / 1_000_000.0
}

// MARK: - TurboModule
//
// INVARIANT 2: TurboModules with JSI — NOT the legacy bridge. The
// legacy bridge's async NSDictionary serialisation adds latency that would
// distort the very native-latency measurement this probe exists to take.
//
// On a real toolchain this class conforms to the codegen-generated spec
// protocol `NativeP2PNativeProbeSpec` (produced from the TS spec in
// native/ios/NativeP2PNativeProbe.ts — see README). We declare the surface here
// and leave the `@objc` bridging + spec conformance to be regenerated by
// codegen at build time. UNTESTED: codegen wiring must be run under Xcode.
@objc(P2PNativeProbe)
final class P2PNativeProbe: NSObject {

    // The JS event emitter callback. Set by the RN runtime when the
    // NativeEventEmitter attaches. Until then, events are dropped (a monitoring
    // layer must never block or crash the transport it observes — mirrors
    // emitSafe() on the JS side).
    private var emitEvent: ((String, [String: Any]) -> Void)?

    // The single event name the JS collector subscribes to. The JS side routes
    // the payload straight into the L2 EventSink.emit(). See README (b).
    static let jsEventName = "p2p.l2.event"

    @objc
    func setEventEmitter(_ emitter: @escaping (String, [String: Any]) -> Void) {
        self.emitEvent = emitter
    }

    // MARK: Emit helper — the ONLY path events leave the native side.
    private func emitL2(_ event: [String: Any]) {
        // Never throw across the JSI boundary; never block the MCSession
        // delegate thread on the JS side. Best-effort, drop on absence.
        emitEvent?(P2PNativeProbe.jsEventName, event)
    }
}

// MARK: - MCSessionDelegate tap
//
// We do NOT own the app's MCSession; we sit in front of its delegate. The app
// keeps its real delegate; this probe forwards every callback to it after
// tapping (decorator pattern) so behaviour is unchanged (mirrors the JS
// send-wrapping invariant: preserve return value and `this`).
final class P2PSessionDelegateTap: NSObject, MCSessionDelegate {

    private weak var wrapped: MCSessionDelegate?
    private let probe: P2PNativeProbe

    // Correlation metadata the app must supply per outbound message so native
    // events carry the SAME msgId/corrId/method as the JS envelope. Without
    // this the native leg cannot be stitched to the JS timeline. Keyed by a
    // hash the app computes over the outgoing Data (see README (a)).
    private var pendingMeta: [Int: OutgoingMeta] = [:]
    private let metaLock = NSLock()

    struct OutgoingMeta {
        let msgId: String
        let corrId: String
        let method: String
        let kind: String   // "req" | "res" | "event" | "ack" | "err"
        let src: String
        let dst: String
        let ts: Double     // sender wall clock epoch ms
        let hlc: String
    }

    init(wrapping delegate: MCSessionDelegate?, probe: P2PNativeProbe) {
        self.wrapped = delegate
        self.probe = probe
        super.init()
    }

    // Called by the app just before session.send(...) so we can correlate the
    // subsequent native send with the JS-side envelope identifiers.
    func registerOutgoing(dataHash: Int, meta: OutgoingMeta) {
        metaLock.lock(); defer { metaLock.unlock() }
        pendingMeta[dataHash] = meta
    }

    // MARK: Outbound tap
    //
    // Call this from the app's send wrapper (see README) around
    // `try session.send(data, toPeers:, with:)`. We open an os_signpost
    // interval spanning the native send and emit a "message.out" L2 event.
    func tapSend(data: Data, toPeers peers: [MCPeerID]) {
        let signpostID = OSSignpostID(log: p2pSignpostLog)
        os_signpost(.begin, log: p2pSignpostLog, name: "mc.send", signpostID: signpostID,
                    "bytes=%d peers=%d", data.count, peers.count)

        let meta = takeMeta(for: data.hashValue)
        var event: [String: Any] = [
            L2Field.type: "message.out",
            L2Field.t: monotonicMillis(),
            L2Field.transport: kTransport,
            L2Field.bytes: data.count,
        ]
        if let m = meta {
            event[L2Field.msgId] = m.msgId
            event[L2Field.corrId] = m.corrId
            event[L2Field.method] = m.method
            event[L2Field.kind] = m.kind
            event[L2Field.src] = m.src
            event[L2Field.dst] = m.dst
            event[L2Field.peerId] = m.dst
            event[L2Field.ts] = m.ts
            event[L2Field.hlc] = m.hlc
        }
        probe.emitL2Public(event)

        os_signpost(.end, log: p2pSignpostLog, name: "mc.send", signpostID: signpostID,
                    "emitted")
    }

    private func takeMeta(for hash: Int) -> OutgoingMeta? {
        metaLock.lock(); defer { metaLock.unlock() }
        return pendingMeta.removeValue(forKey: hash)
    }

    // MARK: MCSessionDelegate — inbound tap + forward
    func session(_ session: MCSession, didReceive data: Data, fromPeer peerID: MCPeerID) {
        let signpostID = OSSignpostID(log: p2pSignpostLog)
        os_signpost(.begin, log: p2pSignpostLog, name: "mc.recv", signpostID: signpostID,
                    "bytes=%d from=%{public}@", data.count, peerID.displayName)

        // The native side cannot know msgId/corrId/method/hlc without decoding
        // the payload envelope. We deliberately do NOT decode here (that is L0's
        // job and would duplicate hrpc-inspector-protocol). We emit the transport-level
        // facts (bytes, src, t) and let L2's correlator stitch by decoding the
        // payload downstream — exactly as the JS message.in path does.
        let event: [String: Any] = [
            L2Field.type: "message.in",
            L2Field.t: monotonicMillis(),
            L2Field.transport: kTransport,
            L2Field.bytes: data.count,
            L2Field.src: peerID.displayName,
            L2Field.peerId: peerID.displayName,
        ]
        probe.emitL2Public(event)

        os_signpost(.end, log: p2pSignpostLog, name: "mc.recv", signpostID: signpostID,
                    "emitted")

        // Forward to the app's real delegate — behaviour must be unchanged.
        wrapped?.session(session, didReceive: data, fromPeer: peerID)
    }

    func session(_ session: MCSession, peer peerID: MCPeerID, didChange state: MCSessionState) {
        let stateName: String
        switch state {
        case .notConnected: stateName = "notConnected"
        case .connecting:   stateName = "connecting"
        case .connected:    stateName = "connected"
        @unknown default:   stateName = "unknown"
        }
        probe.emitL2Public([
            L2Field.type: "conn.state",
            L2Field.t: monotonicMillis(),
            L2Field.transport: kTransport,
            L2Field.peerId: peerID.displayName,
            "conn": stateName,
        ])
        wrapped?.session(session, peer: peerID, didChange: state)
    }

    // Remaining MCSessionDelegate methods are pure pass-through — the probe adds
    // nothing to stream/resource transfer beyond the byte-level send/receive tap.
    func session(_ session: MCSession, didReceive stream: InputStream, withName streamName: String, fromPeer peerID: MCPeerID) {
        wrapped?.session(session, didReceive: stream, withName: streamName, fromPeer: peerID)
    }
    func session(_ session: MCSession, didStartReceivingResourceWithName resourceName: String, fromPeer peerID: MCPeerID, with progress: Progress) {
        wrapped?.session(session, didStartReceivingResourceWithName: resourceName, fromPeer: peerID, with: progress)
    }
    func session(_ session: MCSession, didFinishReceivingResourceWithName resourceName: String, fromPeer peerID: MCPeerID, at localURL: URL?, withError error: Error?) {
        wrapped?.session(session, didFinishReceivingResourceWithName: resourceName, fromPeer: peerID, at: localURL, withError: error)
    }
}

// Bridge the private emit to the delegate tap without exposing the emitter.
extension P2PNativeProbe {
    func emitL2Public(_ event: [String: Any]) { emitL2(event) }
}
